### ISSUE TITLE
项目还在维护吗？

### ISSUE THREAD

**Issue by dancerphil** [ywmaggie/evol#11]
看起来这是一个不完整的网站，有计划上线吗？

如果有维护计划的话，我可以提一些 pr 把它做完。

**Comment by ywmaggie** [comment]
哈哈，你好，谢谢关注！因为一些privacy issue，我们把整个项目移到bitbucket上了。

如果你有兴趣的话，欢迎加入我们攻略组，微博@LINK攻略组-恋与制作人 

谢谢！
